# Generated by Django 6.0 on 2026-01-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название роли"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание роли"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("article", "Статья"),
                            ("product", "Товар"),
                            ("user", "Пользователь"),
                            ("order", "Заказ"),
                            ("category", "Категория"),
                        ],
                        max_length=50,
                        verbose_name="Ресурс",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("read", "Чтение"),
                            ("update", "Обновление"),
                            ("delete", "Удаление"),
                            ("publish", "Публикация"),
                            ("approve", "Одобрение"),
                        ],
                        max_length=50,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text="Уникальное имя разрешения (например: article.create)",
                        max_length=100,
                        unique=True,
                        verbose_name="Кодовое имя",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Разрешение",
                "verbose_name_plural": "Разрешения",
                "ordering": ["resource", "action"],
                "unique_together": {("resource", "action")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата назначения"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="auth_system.permission",
                        verbose_name="Разрешение",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="auth_system.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разрешение роли",
                "verbose_name_plural": "Разрешения ролей",
                "unique_together": {("role", "permission")},
            },
        ),
    ]
