# Generated by Django 6.0 on 2026-01-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="auth_system.role",
                verbose_name="Роль",
            ),
        ),
    ]
